apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  namespace: sample-httpd-ns
  name: sample-tgb
spec:
  serviceRef:
    name: service-sample-httpd
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-1:000000000000:targetgroup/httpd-00000000000000000000000000/xxxxxxxxxxxxxxxx
  targetType: ip
  networking:
    ingress:
    - from:
      - securityGroup:
          groupID: sg-00000000000000000
      ports:
      - protocol: TCP
