apiVersion: v1
kind: Namespace
metadata:
  name: sample-httpd-ns
---
apiVersion: v1
kind: Service
metadata:
  name: service-sample-httpd
  namespace: sample-httpd-ns
  labels:
    app: sample-httpd
spec:
  selector:
    app: sample-httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: sample-httpd-ns
  labels:
    app: sample-httpd
spec:
  selector:
    matchLabels:
      app: sample-httpd
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-httpd
    spec:
      containers:
      - name: httpd
        image: public.ecr.aws/docker/library/httpd:latest
        ports:
        - containerPort: 80